# -*- coding: utf-8 -*-
"""database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhQXUrrd-3slgQj9Gm61OhAcZHiHIfRM

# Database Connection Layer

This module is responsible for establishing a connection between the FastAPI backend and MongoDB Atlas.

The connection string is loaded from a .env file rather than being hardcoded into the source code.

This approach improves:

- Security
- Maintainability
- Deployment flexibility

The module exposes two collections:

- papers
- chunks

which are reused throughout the application.
"""

import os
from pathlib import Path
from pymongo import MongoClient
from dotenv import load_dotenv

# Load .env from the project root
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("DB_NAME", "pdf_papers_ai_agent")

if not MONGO_URI:
    raise ValueError("MONGO_URI is missing. Check your .env file.")

client = MongoClient(MONGO_URI)
db = client[DB_NAME]

papers_col = db["papers"]
chunks_col = db["chunks"]