# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhQXUrrd-3slgQj9Gm61OhAcZHiHIfRM

# FastAPI Application

This module defines the REST API interface for the retrieval system.

The API acts as the communication layer between users and the backend services.

Implemented endpoints:

- GET /
- GET /stats
- POST /search
- POST /ingest

The API was tested using Swagger UI and serves as the foundation for future web applications, chatbots, and GraphRAG systems.
"""

from fastapi import FastAPI
from app.schemas import SearchRequest
from app.database import papers_col, chunks_col
from app.retrieval import search_chunks

app = FastAPI(
    title="PDF Papers AI Agent - D2 API",
    description="FastAPI backend for MongoDB, Qdrant, Hybrid Retrieval, and GraphRAG preparation.",
    version="1.0"
)

@app.get("/")
def home():
    return {
        "message": "PDF Papers AI Agent API is running"
    }

@app.get("/stats")
def stats():
    return {
        "papers": papers_col.count_documents({}),
        "chunks": chunks_col.count_documents({})
    }

@app.post("/search")
def search(request: SearchRequest):
    results = search_chunks(request.query, request.top_k)

    return {
        "query": request.query,
        "top_k": request.top_k,
        "results_count": len(results),
        "results": results
    }

@app.post("/ingest")
def ingest():
    return {
        "status": "completed",
        "message": "Data was already ingested from D1 chunks into MongoDB.",
        "database": "pdf_papers_ai_agent",
        "collections": ["papers", "chunks"],
        "papers": papers_col.count_documents({}),
        "chunks": chunks_col.count_documents({})
    }