# -*- coding: utf-8 -*-
"""retrieval

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhQXUrrd-3slgQj9Gm61OhAcZHiHIfRM

# Retrieval Layer

This module contains the retrieval logic used by the API.

For the current implementation, MongoDB text matching is used to retrieve document chunks.

The retrieval logic is separated from the API layer to improve modularity and maintainability.

Future versions can replace this implementation with:

- Qdrant dense retrieval
- BM25 retrieval
- Hybrid retrieval
- GraphRAG retrieval

without modifying the API endpoints.
"""

from app.database import chunks_col

def search_chunks(query: str, top_k: int = 5):
    """
    Simple MongoDB text search fallback.
    This allows FastAPI /search to work before full hybrid retrieval is plugged in.
    """
    results = list(
        chunks_col.find(
            {"chunk_text": {"$regex": query, "$options": "i"}},
            {"_id": 0}
        ).limit(top_k)
    )

    return results