# -*- coding: utf-8 -*-
"""schema

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhQXUrrd-3slgQj9Gm61OhAcZHiHIfRM

# API Request Schema

This file defines the structure of incoming API requests.

FastAPI uses Pydantic models to validate user input before processing.

The SearchRequest model standardizes retrieval requests by requiring:

- query: search text
- top_k: number of results to return

This design improves API reliability and prevents invalid requests from reaching the retrieval layer.
"""

from pydantic import BaseModel

class SearchRequest(BaseModel):
    query: str
    top_k: int = 5